In [1]:
import os
import numpy as np
import pandas as pd
import cv2
from datetime import *
from imu_video_synch import *
from zurich_move_data_extraction import *
from utilities import *
from activity_count_function import *

C:\Users\Pierre-Louis\anaconda3\lib\site-packages\numpy\_distributor_init.py:30: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\Pierre-Louis\anaconda3\lib\site-packages\numpy\.libs\libopenblas.QVLO2T66WEPI7JZ63PS3HMOHFEY472BC.gfortran-win_amd64.dll
C:\Users\Pierre-Louis\anaconda3\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  warnings.warn("loaded more than 1 DLL from .libs:"

In [2]:
# Path 
initial_path = 'X:\ZM data DB study\FHT001\T0'#'../dataset_Eva'
participant_id = 'jumpExp_230502_150257.mat'
imu_path = os.path.join(initial_path, participant_id)

# Add trimming dates from Excel file corresponding to the participant 
start_date = '2023-05-02 15:05:00.000'
end_date = '2023-05-04 14:46:00.000'

In [3]:
imu_path

'X:\\ZM data DB study\\FHT001\\T0\\jumpExp_230502_150257.mat'

In [4]:
# Define the sensor placements, sensor features, and dataframe features
sensor_placement = ['LW', 'RW', 'chest']
matlab_sensor_features = ['acc', 'gyro', 'quat', 'accHiG', 'magneto', 'press']
sensor_features = ['acc_x', 'acc_y', 'acc_z', 'gyro_x', 'gyro_y', 'gyro_z', 'quat_0', 'quat_1', 'quat_2',
                   'quat_3', 'accHiG_x', 'accHiG_y', 'accHiG_z', 'magneto_x', 'magneto_y', 'magneto_z', 'press']
sensor_9DOF_features = ['accX', 'accY', 'accZ', 'gyroX', 'gyroY', 'gyroZ',
                       'magnetoX', 'magnetoY', 'magnetoZ']
sensor_acc_features =  ['acc_x', 'acc_y', 'acc_z']


#Extract useful stuff
header = extract_header_data_from_mat_file(imu_path)
sampling_freq =get_sampling_freq(header)
time_array = extract_time_data_from_mat_file(imu_path)
recording_time = get_recording_time(time_array)

In [5]:
# Get the optimal group parameters for AC and GM

In [6]:
header

,durationStr,freq,start,startStr,stop,stopStr,tsErrorSensorIDs
0,2 d   2 1 h   9 m   2 6 s ,50.0,1.683040e+09,2 0 2 3 / 0 5 / 0 2   1 5 : 0 2 : 5 7 . 0 0 0 ,1.683289e+09,2 0 2 3 / 0 5 / 0 5   1 2 : 1 2 : 2 3 . 0 0 0 ,                

In [7]:
sampling_freq

50.0

In [8]:
time_array

               time
0              0.00
1              0.02
2              0.04
3              0.06
4              0.08
...             ...
12448296  248965.92
12448297  248965.94
12448298  248965.96
12448299  248965.98
12448300  248966.00

[12448301 rows x 1 columns]

In [9]:
recording_time

248966

In [10]:
def extract_sensors_data_from_mat_file(file_path: str, sensor_placement, sensors_features, dataframe_features, num_sensors=3) -> dict:
    """
    Extracts data from a .mat file and returns a dictionary of dataframes.

    Args:
        file_path (str): The path to the .mat file.
        sensor_placement (list): List of sensor placements ('LW', 'RW', 'chest').
        sensors_features (list): List of sensor features to extract.
        dataframe_features (list): List of column names for the dataframes.
        num_sensors (int): Number of sensors present (2 or 3).

    Returns:
        dict: A dictionary of dataframes, where the keys are the sensor placements
            ('LW', 'RW', 'chest') and the values are dataframes with the sensor data.
    """
    dfs = {placement: pd.DataFrame(columns=dataframe_features) for placement in sensor_placement}
    
    with h5py.File(file_path, 'r') as mat_file:
        for placement_idx, placement in enumerate(sensor_placement):
            if num_sensors == 2 and placement == 'chest':
                # Skip processing the chest sensor if there are only 2 sensors
                continue
            
            if placement_idx >= len(mat_file['jumpExp']['sensors'][sensors_features[0]]):
                # Handle cases where the placement index is out of range
                print(f"Skipping {placement} data due to index out of range.")
                continue

            feature_data = {}
            for feature in sensors_features:
                sensors_data = mat_file['jumpExp']['sensors'][feature]
                ref = sensors_data[placement_idx, 0]
                if feature == 'press':
                    feature_data[feature] = np.array(mat_file[ref]).T
                else:
                    feature_data[feature] = np.array(mat_file[ref])
            data = np.concatenate([feature_data[feature] for feature in sensors_features], axis=0)
            df = pd.DataFrame(data.T, columns=dataframe_features)
            dfs[placement] = df
            
    return dfs

In [11]:
dfs = extract_sensors_data_from_mat_file(imu_path, sensor_placement, matlab_sensor_features, sensor_features, num_sensors = 2)
#Usefull export to csv (for SimuLOOP script)
#export_to_csv(file_path, dfs, sensor_placement, matlab_sensor_features, sensor_features)
acc_LW = dfs['LW'][['acc_x', 'acc_y', 'acc_z']]
acc_RW = dfs['RW'][['acc_x', 'acc_y', 'acc_z']]
gyro_LW = dfs['LW'][['gyro_x', 'gyro_y', 'gyro_z']]
gyro_RW = dfs['RW'][['gyro_x', 'gyro_y', 'gyro_z']]
mag_LW = dfs['LW'][['magneto_x', 'magneto_y', 'magneto_z']]
quat_sensor_LW = dfs['LW'][['quat_0', 'quat_1', 'quat_2','quat_3']]
LW_data = dfs['LW']
RW_data = dfs['RW']
chest_data = dfs['chest']

In [12]:
dfs

{'LW':              acc_x     acc_y     acc_z      gyro_x      gyro_y      gyro_z  \
 0        -0.016384 -2.335981 -0.307389  -45.795686   90.693261  151.107934
 1        -0.277900 -2.071634 -0.949411  -26.655530  106.798184   85.322196
 2        -0.467208 -1.845471 -1.400375    6.509488  121.689873   81.812395
 3        -0.544075 -1.773151 -1.218579  -17.487459  129.857321   73.444144
 4        -0.416559 -1.421982 -1.206728  -86.507854   88.297179   57.635186
 ...            ...       ...       ...         ...         ...         ...
 12448296  0.752951  0.229913  0.836043  103.880728  -91.831693  -60.026841
 12448297  0.588679 -0.082030  0.345164  116.037948  -54.684779  -76.876458
 12448298  0.766346  0.053310  0.489769   52.173996  -35.584882  -51.874622
 12448299  1.049548  0.430538  0.966601  -36.755587  -27.230986    5.507444
 12448300  1.083831  0.661703  0.863446  -63.941368  -30.072212   35.566474

             quat_0    quat_1    quat_2    quat_3  accHiG_x  accHiG_y  \
 0         0.279378 -0.689790 -0.602946  0.287451 -0.140486 -0.882211
 1         0.280780 -0.706195 -0.587263  0.278545 -0.265987 -0.994124
 2         0.287663 -0.720007 -0.572330  0.266938 -0.338399 -0.804789
 3         0.296494 -0.733715 -0.556258  0.253613 -0.455026 -0.634324
 4         0.296744 -0.746337 -0.545486  0.239613 -0.552565 -0.600630
 ...            ...       ...       ...       ...       ...       ...
 12448296  0.919803  0.172034 -0.274425  0.221482  0.167590  0.219575
 12448297  0.915488  0.197251 -0.278050  0.213632  0.179728  0.318305
 12448298  0.912924  0.214791 -0.279655  0.205532  0.094803  0.194151
 12448299  0.912188  0.215481 -0.284279  0.201649 -0.013233  0.231490
 12448300  0.911914  0.206052 -0.291961  0.201775  0.142036  0.418979

           accHiG_z   magneto_x   magneto_y   magneto_z    press
 0        -0.563888  271.794112  238.190365   44.999911  1014.42
 1        -0.494114  271.821978  238.235965   45.000333  1014.42
 2        -0.796791  271.717960  238.065754   44.998757  1014.42
 3        -0.992042  272.106230  238.701104   45.004640  1014.42
 4        -0.917605  270.656932  236.329525   44.982681  1014.42
 ...            ...         ...         ...         ...      ...
 12448296  0.404190  146.988910   78.014578  -96.639441  1013.19
 12448297  0.237564  147.041398   77.945582  -96.452772  1013.19
 12448298  0.011417  146.845466   78.203137  -97.149593  1013.19
 12448299 -0.024754  147.576862   77.241705  -94.548418  1013.19
 12448300  0.174358  144.846629   80.830641 -104.258359  1013.19

 [12448301 rows x 17 columns],
 'RW':              acc_x     acc_y     acc_z      gyro_x     gyro_y      gyro_z  \
 0         0.653965 -1.899731  0.138177   38.257227  -7.399807  -53.487924
 1         0.791606 -1.794507  0.077553  -79.086773 -59.327893  -83.679450
 2         0.837456 -1.786908  0.046443 -114.565329 -14.858653 -121.762456
 3         0.912274 -1.718224 -0.047815 -141.186904   2.249211 -125.589013
 4         0.941776 -1.582253 -0.118750 -166.202450  10.591317 -106.003871
 ...            ...       ...       ...         ...        ...         ...
 12448296  0.751681 -2.019792 -0.611046    0.656495  11.385146    4.288067
 12448297  0.821517 -1.927186 -0.746274    8.368198  14.707497  -10.519080
 12448298  0.880330 -1.742050 -0.929449   18.630704  24.708405  -24.757890
 12448299  0.790591 -1.667196 -1.088744   19.657259  35.261859  -36.557350
 12448300  0.830263 -1.635817 -1.298836   18.230621  41.957515  -25.014205

             quat_0    quat_1    quat_2    quat_3  accHiG_x  accHiG_y  \
 0         0.506409 -0.603340 -0.603776  0.122485 -0.165626 -0.360873
 1         0.500344 -0.598232 -0.614820  0.117242 -0.110034 -0.494707
 2         0.488028 -0.595211 -0.630278  0.101592 -0.039934 -0.445307
 3         0.477661 -0.591106 -0.645354  0.077044 -0.018912 -0.486806
 4         0.464101 -0.590810 -0.658134  0.049276 -0.015512 -0.370057
 ...            ...       ...       ...       ...       ...       ...
 12448296  0.305393 -0.175723 -0.794205  0.495071  0.026981 -0.340699
 12448297  0.307894 -0.175966 -0.793182  0.495075  0.054140 -0.451967
 12448298  0.312801 -0.174088 -0.791597  0.495203  0.045688 -0.517033
 12448299  0.320662 -0.171194 -0.789273  0.494885  0.055796 -0.360033
 12448300  0.328918 -0.169317 -0.786802  0.494059  0.013821 -0.316643

           accHiG_z   magneto_x   magneto_y   magneto_z        press
 0         0.807876  243.600292  424.799644  318.000301  1009.170000
 1         0.617447  243.599773  424.800017  318.000099  1009.170001
 2         0.489127  243.600616  424.800290  317.999305  1009.169998
 3         0.544618  243.597763  424.798824  318.002680  1009.170009
 4         0.549263  243.608330  424.804415  317.989974  1009.169968
 ...            ...         ...         ...         ...          ...
 12448296  0.337509   75.013063  358.800441  209.393103  1007.250000
 12448297  0.269329   74.951239  358.798355  209.425747  1007.250000
 12448298  0.152868   75.182012  358.806139  209.303895  1007.250000
 12448299  0.089137   74.320605  358.777085  209.758731  1007.250000
 12448300  0.076231   78.886742  358.762738  207.324185  1007.250000

 [12448301 rows x 17 columns],
 'chest': Empty DataFrame
 Columns: [acc_x, acc_y, acc_z, gyro_x, gyro_y, gyro_z, quat_0, quat_1, quat_2, quat_3, accHiG_x, accHiG_y, accHiG_z, magneto_x, magneto_y, magneto_z, press]
 Index: []}

In [13]:
# Add timestamps 
IMU_start_timestamp, IMU_end_timestamp = get_datetime_timestamp(header)

2023-05-02 15:02:57.000000 2023-05-05 12:12:23.000000

In [14]:
timestamps_array = create_timestamps(IMU_start_timestamp, IMU_end_timestamp, 50)
# Add timestamps to raw data
LW_data = pd.concat([timestamps_array, LW_data], axis=1)
RW_data = pd.concat([timestamps_array, RW_data], axis=1)
chest_data = pd.concat([timestamps_array, chest_data], axis=1)

In [15]:
RW_data

,timestamp,acc_x,acc_y,acc_z,gyro_x,gyro_y,gyro_z,quat_0,quat_1,quat_2,quat_3,accHiG_x,accHiG_y,accHiG_z,magneto_x,magneto_y,magneto_z,press
0,2023-05-02 15:02:57.000,0.653965,-1.899731,0.138177,38.257227,-7.399807,-53.487924,0.506409,-0.603340,-0.603776,0.122485,-0.165626,-0.360873,0.807876,243.600292,424.799644,318.000301,1009.170000
1,2023-05-02 15:02:57.020,0.791606,-1.794507,0.077553,-79.086773,-59.327893,-83.679450,0.500344,-0.598232,-0.614820,0.117242,-0.110034,-0.494707,0.617447,243.599773,424.800017,318.000099,1009.170001
2,2023-05-02 15:02:57.040,0.837456,-1.786908,0.046443,-114.565329,-14.858653,-121.762456,0.488028,-0.595211,-0.630278,0.101592,-0.039934,-0.445307,0.489127,243.600616,424.800290,317.999305,1009.169998
3,2023-05-02 15:02:57.060,0.912274,-1.718224,-0.047815,-141.186904,2.249211,-125.589013,0.477661,-0.591106,-0.645354,0.077044,-0.018912,-0.486806,0.544618,243.597763,424.798824,318.002680,1009.170009
4,2023-05-02 15:02:57.080,0.941776,-1.582253,-0.118750,-166.202450,10.591317,-106.003871,0.464101,-0.590810,-0.658134,0.049276,-0.015512,-0.370057,0.549263,243.608330,424.804415,317.989974,1009.169968
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12448296,2023-05-05 12:12:22.920,0.751681,-2.019792,-0.611046,0.656495,11.385146,4.288067,0.305393,-0.175723,-0.794205,0.495071,0.026981,-0.340699,0.337509,75.013063,358.800441,209.393103,1007.250000
12448297,2023-05-05 12:12:22.940,0.821517,-1.927186,-0.746274,8.368198,14.707497,-10.519080,0.307894,-0.175966,-0.793182,0.495075,0.054140,-0.451967,0.269329,74.951239,358.798355,209.425747,1007.250000
12448298,2023-05-05 12:12:22.960,0.880330,-1.742050,-0.929449,18.630704,24.708405,-24.757890,0.312801,-0.174088,-0.791597,0.495203,0.045688,-0.517033,0.152868,75.182012,358.806139,209.303895,1007.250000
12448299,2023-05-05 12:12:22.980,0.790591,-1.667196,-1.088744,19.657259,35.261859,-36.557350,0.320662,-0.171194,-0.789273,0.494885,0.055796,-0.360033,0.089137,74.320605,358.777085,209.758731,1007.250000
12448300,2023-05-05 12:12:23.000,0.830263,-1.635817,-1.298836,18.230621,41.957515,-25.014205,0.328918,-0.169317,-0.786802,0.494059,0.013821,-0.316643,0.076231,78.886742,358.762738,207.324185,1007.250000

In [16]:
LW_data

,timestamp,acc_x,acc_y,acc_z,gyro_x,gyro_y,gyro_z,quat_0,quat_1,quat_2,quat_3,accHiG_x,accHiG_y,accHiG_z,magneto_x,magneto_y,magneto_z,press
0,2023-05-02 15:02:57.000,-0.016384,-2.335981,-0.307389,-45.795686,90.693261,151.107934,0.279378,-0.689790,-0.602946,0.287451,-0.140486,-0.882211,-0.563888,271.794112,238.190365,44.999911,1014.42
1,2023-05-02 15:02:57.020,-0.277900,-2.071634,-0.949411,-26.655530,106.798184,85.322196,0.280780,-0.706195,-0.587263,0.278545,-0.265987,-0.994124,-0.494114,271.821978,238.235965,45.000333,1014.42
2,2023-05-02 15:02:57.040,-0.467208,-1.845471,-1.400375,6.509488,121.689873,81.812395,0.287663,-0.720007,-0.572330,0.266938,-0.338399,-0.804789,-0.796791,271.717960,238.065754,44.998757,1014.42
3,2023-05-02 15:02:57.060,-0.544075,-1.773151,-1.218579,-17.487459,129.857321,73.444144,0.296494,-0.733715,-0.556258,0.253613,-0.455026,-0.634324,-0.992042,272.106230,238.701104,45.004640,1014.42
4,2023-05-02 15:02:57.080,-0.416559,-1.421982,-1.206728,-86.507854,88.297179,57.635186,0.296744,-0.746337,-0.545486,0.239613,-0.552565,-0.600630,-0.917605,270.656932,236.329525,44.982681,1014.42
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
12448296,2023-05-05 12:12:22.920,0.752951,0.229913,0.836043,103.880728,-91.831693,-60.026841,0.919803,0.172034,-0.274425,0.221482,0.167590,0.219575,0.404190,146.988910,78.014578,-96.639441,1013.19
12448297,2023-05-05 12:12:22.940,0.588679,-0.082030,0.345164,116.037948,-54.684779,-76.876458,0.915488,0.197251,-0.278050,0.213632,0.179728,0.318305,0.237564,147.041398,77.945582,-96.452772,1013.19
12448298,2023-05-05 12:12:22.960,0.766346,0.053310,0.489769,52.173996,-35.584882,-51.874622,0.912924,0.214791,-0.279655,0.205532,0.094803,0.194151,0.011417,146.845466,78.203137,-97.149593,1013.19
12448299,2023-05-05 12:12:22.980,1.049548,0.430538,0.966601,-36.755587,-27.230986,5.507444,0.912188,0.215481,-0.284279,0.201649,-0.013233,0.231490,-0.024754,147.576862,77.241705,-94.548418,1013.19
12448300,2023-05-05 12:12:23.000,1.083831,0.661703,0.863446,-63.941368,-30.072212,35.566474,0.911914,0.206052,-0.291961,0.201775,0.142036,0.418979,0.174358,144.846629,80.830641,-104.258359,1013.19

In [17]:
import pandas as pd

def trim_dataframe_by_time(df, start_time, end_time):
    df['timestamp'] = pd.to_datetime(df['timestamp'])  # Convert 'timestamp' column to datetime format
    mask = (df['timestamp'] >= start_time) & (df['timestamp'] <= end_time)  # Create a boolean mask
    trimmed_df = df[mask]  # Apply the mask to the DataFrame
    return trimmed_df

In [18]:
trimmed_LW_data = trim_dataframe_by_time(LW_data, start_date, end_date)

In [19]:
trimmed_LW_data

,timestamp,acc_x,acc_y,acc_z,gyro_x,gyro_y,gyro_z,quat_0,quat_1,quat_2,quat_3,accHiG_x,accHiG_y,accHiG_z,magneto_x,magneto_y,magneto_z,press
6150,2023-05-02 15:05:00.000,0.257236,-0.953894,-2.155503,-8.468026,12.627281,17.432138,-0.180711,0.961159,-0.176967,0.110449,-0.111447,-0.126481,-1.415802,73.800019,121.800000,6.000050,1011.36
6151,2023-05-02 15:05:00.020,0.206762,-1.022367,-2.089222,-10.369600,13.519582,13.697238,-0.178986,0.960715,-0.180174,0.111925,-0.130532,-0.187660,-1.333170,73.799994,121.800000,5.999985,1011.36
6152,2023-05-02 15:05:00.040,0.160493,-1.071355,-2.080173,-6.946993,6.908022,10.951560,-0.177621,0.960384,-0.182714,0.112823,-0.190701,-0.238445,-1.314979,73.800005,121.800002,6.000010,1011.36
6153,2023-05-02 15:05:00.060,0.176386,-1.105825,-2.161856,-1.184349,0.150259,8.006143,-0.177315,0.960123,-0.184457,0.112687,-0.196462,-0.241073,-1.310054,73.799986,121.799993,5.999974,1011.36
6154,2023-05-02 15:05:00.080,0.188561,-1.112369,-2.237017,4.196168,-1.090945,2.352113,-0.178049,0.959892,-0.185201,0.112280,-0.193856,-0.286660,-1.399879,73.800050,121.800025,6.000094,1011.36
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8589146,2023-05-04 14:45:59.920,0.582381,-1.782374,0.410584,0.100885,0.626482,0.222289,-0.678508,0.434677,0.419225,-0.418250,-0.057321,-0.539193,0.044503,82.800008,119.399953,-48.599882,1010.88
8589147,2023-05-04 14:45:59.940,0.572554,-1.764320,0.413269,-0.250313,0.704418,-0.129038,-0.678535,0.434756,0.419309,-0.418040,-0.047831,-0.576774,0.013193,82.799998,119.400012,-48.600032,1010.88
8589148,2023-05-04 14:45:59.960,0.569692,-1.791281,0.373820,0.211586,0.065104,-0.024407,-0.678581,0.434727,0.419418,-0.417887,-0.044317,-0.588820,-0.048146,82.800000,119.399997,-48.599991,1010.88
8589149,2023-05-04 14:45:59.980,0.549099,-1.772223,0.365380,-0.707728,-0.312468,-0.165695,-0.678548,0.434723,0.419638,-0.417723,-0.095585,-0.579887,-0.007767,82.800002,119.400000,-48.600005,1010.88
8589150,2023-05-04 14:46:00.000,0.541454,-1.755214,0.348019,-1.380279,-0.149660,-0.052018,-0.678429,0.434828,0.419922,-0.417521,-0.053507,-0.631897,0.002326,82.799993,119.400005,-48.599989,1010.88

In [ ]:
# Save the trimmed data
initial_path = r'X:\ZM data DB study\FHT001\T0'  # Use raw string literal to handle backslashes

# Assuming you want to save the trimmed_LW_data DataFrame
trimmed_LW_data.to_csv(initial_path + '/trimmed_LW_data.csv', index=False)

print("Trimmed data for LW saved to:", initial_path + '/trimmed_LW_data.csv')

In [ ]:
trimmed_RW_data = trim_dataframe_by_time(RW_data, start_date, end_date)

In [ ]:
trimmed_RW_data

In [ ]:
# Save the trimmed data
initial_path = r'X:\ZM data DB study\FHT001\T0'  # Use raw string literal to handle backslashes

# Assuming you want to save the trimmed_LW_data DataFrame
trimmed_RW_data.to_csv(initial_path + '/trimmed_RW_data.csv', index=False)

print("Trimmed data for LW saved to:", initial_path + '/trimmed_RW_data.csv')

In [ ]:
# Compute conventional and optimal AC using optimal thresholds 

#Compute Actigraph Activity Count 
count_brond_ndh, processed_data_ndh = get_counts_brond(trimmed_LW_data)
count_brond_dh, processed_data_dh = get_counts_brond(trimmed_RW_data)
AC_ndh = np.array(count_brond_ndh['AC Brond'])
AC_dh = np.array(count_brond_dh['AC Brond'])

In [ ]:
plot_actigraph_count(count_brond_ndh), plot_actigraph_count(count_brond_dh)

In [ ]:
AC_ndh

In [ ]:
def compute_prediction_ac(testing_count_brond_ndh, testing_count_brond_dh,
                                  conventional_threshold_unilateral, opt_threshold_ndh, opt_threshold_dh):
    """
    Compute evaluation metrics for different prediction scenarios.

    Args:
        testing_count_brond_ndh (numpy.ndarray): NumPy array containing AC values for the left Upper Limb (NDH).
        testing_count_brond_dh (numpy.ndarray): NumPy array containing AC values for the right  (DH).
        conventional_threshold_unilateral (float): Conventional AC threshold for unilateral prediction.
        opt_threshold_ndh (float): Optimal AC threshold for NDH prediction.
        opt_threshold_dh (float): Optimal AC threshold for DH prediction.

    Returns:
        A dictionary:
        - AC scores dictionary
    """
    # Compute predictions
    testing_ac_ndh_conv = get_prediction_ac(testing_count_brond_ndh, conventional_threshold_unilateral)
    testing_ac_ndh_opt = get_prediction_ac(testing_count_brond_ndh, opt_threshold_ndh)
    testing_ac_dh_conv = get_prediction_ac(testing_count_brond_dh, conventional_threshold_unilateral)
    testing_ac_dh_opt = get_prediction_ac(testing_count_brond_dh, opt_threshold_dh)
    testing_ac_bil_conv = get_prediction_bilateral(testing_count_brond_ndh, conventional_threshold_unilateral,
                                                   testing_count_brond_dh, conventional_threshold_unilateral)
    testing_ac_bil_opt = get_prediction_bilateral(testing_count_brond_ndh, opt_threshold_ndh,
                                                  testing_count_brond_dh, opt_threshold_dh)

    # Compute AC score dictionaries
    ac_scores = {
        'ndh_conv': testing_ac_ndh_conv,
        'ndh_opt': testing_ac_ndh_opt,
        'dh_conv': testing_ac_dh_conv,
        'dh_opt': testing_ac_dh_opt,
        'bil_conv': testing_ac_bil_conv,
        'bil_opt': testing_ac_bil_opt
    }

In [ ]:
compute_prediction_ac(count_brond_ndh, count_brond_dh,
                                  conventional_threshold_unilateral, opt_threshold_ndh, opt_threshold_dh)

In [ ]:
# Compute conventional and optimal GM using optimal FS

In [ ]:
# Compute conventional and optimal GMAC using optimal thresholds and FS

In [ ]:
# Compare both duration of functional arm use between the two approaches: no GT available so only differences between the two